dataset_id = "testing_2236690"
friendly_name = "testing dataset new"
description = "Sample dataset"
location = "US"
project_id = "fluent-buckeye-335714"
table_id = "testing_table2"
source_uris = [ "https://storage.cloud.google.com/bq-data-bucket-22366/sample.csv" ]
source_format = "CSV"
autodetect = true
deletion_protection = false